services:
  openvscode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openvscode
    user: "1000:1000"
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
       - /home/itbttex/vscode-home:/home/workspace:rw
    ports:
      - 3002:3000
    restart: unless-stopped
